controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    vel_cont:
      type: velocity_controllers/JointGroupVelocityController


vel_cont:
  ros__parameters:
    joints:
      - flj
      - frj
      - blj
      - brj
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
      - effort